name: Unit test and Sonar

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
  sonarqube:
    uses: ./.github/workflows/sonar.yml
    secrets: inherit
    needs: test
